### ISSUE TITLE
Callback should be optional

### ISSUE THREAD

**Issue by JeanMeche** [rajeshwarpatlolla/my-angularjs-directives#11]
An exception is thrown when closing the popup if there is no callback defined. 

Shouldn't the callback be optional ?

**Comment by rajeshwarpatlolla** [comment]
Could you please let me know, which directive you are referring to?

**Comment by JeanMeche** [comment]
My mistake, I wanted to post it on the timepicker repo !

**Comment by rajeshwarpatlolla** [comment]
For now this is mandatory. May be in the future releases i will make it as optional. But still i feel getting the selected value back to the controller is always a need.
