### ISSUE TITLE
checkWithCurrentTime function

### ISSUE THREAD

**Issue by jossErnesto** [rajeshwarpatlolla/my-angularjs-directives#12]
in:
if (timeArray[2] === 'PM') {
        timeArray[0] += 12;
      }
should be:
if (timeArray[2] === 'PM') {
      if(timeArray[0]!==12)
          timeArray[0] += 12;
      }
right?

best regards.

**Comment by rajeshwarpatlolla** [comment]
Thanks for your suggestion and code snippet. I have added your suggestion to the code.
