### ISSUE TITLE
usnig standard time meridian to show time

### ISSUE THREAD

**Issue by anshulklr** [rajeshwarpatlolla/my-angularjs-directives#6]
i'm using this for from and to fields and now i want to get the data in the backend in the same manner. how to do this?
because same directive is getting used.

how can i get the data?

**Comment by rajeshwarpatlolla** [comment]
You can use the directive twice for both the `to` and `from` fields. I think this will solve your problem.

**Comment by anshulklr** [comment]
I'm using the directive, but the point is saving it in a variable in the controller

**Comment by rajeshwarpatlolla** [comment]
Did you mean you want to get the string formatted time in to your controller?
If so this does not support as of now.

**Comment by anshulklr** [comment]
then how will i save the time to the controller?

**Comment by rajeshwarpatlolla** [comment]
You have to implement the same logic in your controller to get the string value. I mean logic for converting the epoch to the string.

**Comment by anshulklr** [comment]
okay, i'll do that.
now can u tell me how i can get the selected date saved in a variable in the controller using your datepicker?

**Comment by rajeshwarpatlolla** [comment]
It will be stored in `$scope.currentDate` variable in the respected controller.

**Comment by anshulklr** [comment]
$scope.currentDate is always showing the current date not the selected date.

**Comment by rajeshwarpatlolla** [comment]
May you are making some thing wrong. I tested it and it was working fine. Even people are using this component with out this issue. Could you please check your code once.

**Comment by anshulklr** [comment]
I have checked it, the thing is it shows on the view but the scope value is not updated, I don't know y?

**Comment by rajeshwarpatlolla** [comment]
This feature has been implemented by adding a call back to `ionic-datepicker`. You can use the returned value to manipulate the view.
